CREATE TABLE `table_bpm` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`user` VARCHAR(254) NULL DEFAULT NULL,
	`id_process` BIGINT(20) NULL DEFAULT NULL,
	`state` VARCHAR(254) NULL DEFAULT NULL,
	`date` DATETIME NULL DEFAULT NULL,
	`info` VARCHAR(254) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)
